### ISSUE TITLE
linking on macOS fails: lexer lib is -ll instead of -lfl

### ISSUE THREAD

**Issue by Gairlochan** [vapier/pcalc#1]
Just thought I'd let you know it compiles fine on OS X if you change line 14 of the makefile from:
LDLIBS += -lm lfl
to:
LDLIBS += -lm ll

**Comment by marcastel** [comment]
Hello, just bumped into this... if you're willing to use GNU extensions, here's a permanent fix:

```
UNAME = $(shell uname -s)

ifeq ($(UNAME),Darwin)
	LDLIBS   += -lm -ll
else
	LDLIBS   += -lm -lfl
endif
```
Here's the modified [Makefile](https://github.com/vapier/pcalc/files/2630113/Makefile.gz).

**Comment by vapier** [comment]
does macOS use `flex` and `bison` by default ?  or are you changing those as well ?

it's a bit odd if macOS provided `flex` but not `-lfl`.

**Comment by marcastel** [comment]
I have `/usr/bin/flex`. Don't have a vanilla macOS to check right now. I am assuming it is part of the [Xcode](https://developer.apple.com/xcode/) command line tools that one installs with `xcode-select --install`.

No `bison` by default.

As for the oddness, I don't have the mileage to answer. MacOS being of BSD descent, I would assume this to be historical in the System V vs. BSD race of the 80s (i.e. lex and yacc vs flex and Berkeley yacc).

**Comment by vapier** [comment]
the fix was embarrassingly easier to pull off.  just force it to a compile-time constant and don't link anything in at all.
