### ISSUE TITLE
pcalc install

### ISSUE THREAD

**Issue by Marcoc-008** [vapier/pcalc#2]
I have problem in installing pcalc on my opensuse leap 42.2 machine.

Could you please give me hints ?

Regards,

MarcoC

**Comment by vapier** [comment]
please post the actual commands you're running and the output

**Comment by Marcoc-008** [comment]
Hereafter the actual command:


studio@linux:~> ls pcalc-000.tar.gz
pcalc-000.tar.gz
studio@linux:~> tar xf pcalc-000.tar.gz 
studio@linux:~> cd pcalc-000/
studio@linux:~/pcalc-000> ls 
convert.c  EXAMPLE  help.h     math.c  pcalc.c   pcalcl.l   pcalc.map    pcalc.t
ab.h  print.c  README      skeleton.h  str.c     symbol.h  testorig convert.h  f
unct.c  hocdecl.h  pack    pcalc.h   pcalc.lsm  pcalc.old    pcalc.txt    print.
h  skelcom.h   store.c     str.h     testdat   win32 DISCAIMER  help.c   Makefil
e   pcalc   pcalcl.c  pcalc.mak  pcalc.tab.c  pcalc.y      ptest    skeleton.c  
store.h     symbol.c  testdata 
studio@linux:~/pcalc-000> pcalc 0y01001001
bash: /usr/bin/pcalc: No such file or directory
studio@linux:~/pcalc-000> make install
install pcalc /usr/bin
install: cannot create regular file '/usr/bin/pcalc': Permission denied
Makefile:79: recipe for target 'install' failed
make: *** [install] Error 1
studio@linux:~/pcalc-000> sudo !!
sudo make install
install pcalc /usr/bin
studio@linux:~/pcalc-000> pcalc 0y01001001
bash: /usr/bin/pcalc: No such file or directory
studio@linux:~/pcalc-000> cd /usr/bin/
studio@linux:/usr/bin> ls pcalc
pcalc
studio@linux:/usr/bin> 



I have extracted pcalc-000.tar.gz, then, from within /pcalc-000, I have launched
pcalc as there was an executable in this directory, but without success. Then I
have launched make install, the file was copied in the usr/bin directory, but b
ush told me:

bash: /usr/bin/pcalc: No such file or directory

I have read the README file but there weren't hints about installing pcalc.

Regards,

Marco C

**Comment by vapier** [comment]
installing files into / requires root.  so you need to `sudo make install` or change to root first some other way before trying to install.

**Comment by Marcoc-008** [comment]
I have tried this before, without success. Here the actual commands:

studio@linux:~> cd pcalc-000/
studio@linux:~/pcalc-000> sudo make install
root's password:
install pcalc /usr/bin
studio@linux:~/pcalc-000> pcalc 0y01001001
bash: /usr/bin/pcalc: No such file or directory
studio@linux:~/pcalc-000> 

How can I do ?

Regards,

Marco C

**Comment by vapier** [comment]
sorry, didn't see that you ran sudo already.  you should start with the latest pcalc-v3 release instead of the old/original 000 release.

**Comment by sergeevabc** [comment]
Dear @vapier,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by vapier** [comment]
sure, i've posted one for the latest v4 release.  i gave it a quick test under Wine, but not actual Windows ;).
