### ISSUE TITLE
pcalc.001 & pcalc.002 tests fail depending on accuracy of host math lib

### ISSUE THREAD

**Issue by charlesdaniels** [vapier/pcalc#6]
[testsuite.log](https://github.com/vapier/pcalc/files/2636376/testsuite.log)

The test suite fails on some tests. This appears to be some kind of floating point rounding issue.

This was tested against both afcf2f4d194ec652e466b1ab721d007a807747a6 and v4. 

The tests were run on an OpenBSD 6.4 system on an AMD64 processor. 

Note that the workaround noted in #5 had to be applied in order to run the testes.

**Comment by vapier** [comment]
this is a known problem on systems who don't have floating point numbers that use the same precision as the system i'm building on.  you can see similar failures & debug info in this [Gentoo report](https://bugs.gentoo.org/276801).

pcalc doesn't have a way currently of specifying how many digits of precision to output, but that'd probably be one way of mitigating it (only require the first few leading digits match).

converting to GMP as in #3 would also address this ...

in the meantime, i'll just chalk it up as a known issue.
