### ISSUE TITLE
Binary shift operators don't work

### ISSUE THREAD

**Issue by coldspark29** [vapier/pcalc#8]
When I type

```
$ pcalc 20 < 1
bash: no such file or directory: 1
```

and 
```
$ pcalc 20 << 1
heredoc> 
```

Is this a bug or is the syntax wrong?

**Comment by VittoDan** [comment]
could it be a bash issue since the character "<" and the string "<<" are reserved for putting a file to stdin and for [heredocs](https://en.wikipedia.org/wiki/Here_document) respectively?

**Comment by vapier** [comment]
yes, that error is from the shell. you need to quote the arguments

**Comment by coldspark29** [comment]
Ah yeah thanks
